# Generated by Django 4.1.4 on 2023-03-13 09:06

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_cost_alter_product_discountprice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="category", to="products.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=django_mysql.models.ListCharField(
                models.CharField(
                    choices=[
                        ("w", "white"),
                        ("g", "green"),
                        ("r", "red"),
                        ("bu", "blue"),
                        ("bk", "black"),
                    ],
                    max_length=10,
                ),
                max_length=66,
                size=6,
            ),
        ),
    ]
